### PR TITLE
m1 support

### PR DESCRIPTION
**Pull request by aprivette**
Hey!  Thanks for your work on this.  Greenworks was giving me a headache.

I was hoping to get M1 support going here, but since github actions doesn't support that yet (outside of self hosting it seems), I wasn't sure how it would be best to handle it.  This PR just basically copies the arm64 binary I built into the dist folder before publish.  I will admit this solution isn't ideal, but I'm open to ideas!

### CODE REVIEW

**Comment by ceifa** [comment]
Nice addition! The only problem is that I don't have a M1 here to continue giving support on this...
Related: https://github.com/github/roadmap/issues/528

**Comment by aprivette** [comment]
Ah, fair enough!  I'd donate a runner if I had a desktop mac lol.  You're welcome to ping me whenever you need an updated m1 build since it'd be a fairly infrequent task, though I'll concede that it would be a clunky process haha.

**Comment by ceifa** [comment]
Hey @aprivette, did you have any trouble running steamworks.js on M1? I just thought we had some problems with platform-specific bindings before: https://github.com/Noxime/steamworks-rs/pull/106

**Comment by aprivette** [comment]
@ceifa I'll admit I didn't test this extensively but it did work.  If there's anything specific you'd like me to test I'm happy to!

**Pull request merged**
